sudo: false

os: osx

language: node_js

node_js: 8

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

before_install:
  - brew update
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - npm install

script:
  - node --version
  - npm run package-mac
