sudo: false

os: osx

language: node_js

node_js: 8

cache:
  directories:
    - node_modules
    - app/node_modules

before_install:
  - brew update
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - git config --global url."https://${GH_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN


install:
  - npm whoami
  - npm install

script:
  - node --version
  - npm run package-mac
