os: Visual Studio 2015

platform: x64

environment:
  nodejs_version: 8

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - ps: '"//registry.npmjs.org/:_authToken=$env:NPM_TOKEN`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - git config --global url."https://%GH_TOKEN%:x-oauth-basic@github.com/".insteadOf "https://github.com/"
  - npm install

test_script:
  - node --version
  - npm run package-win
